### PR TITLE
Make it more fancy

### PR DESCRIPTION
**Pull request by ghost**
Just a small modification to make it look fancy

### CODE REVIEW

**Comment by ghost** [comment]
By the way, i am suspended on glitch support till november the 10

**Comment by trentwiles** [comment]
What happened?

**Comment by ghost** [comment]
https://github.com/LankyBox01/LankyBox01/issues/9

**Comment by trentwiles** [comment]
This probably will not work as you cannot nest breaks.

**Comment by ghost** [comment]
shall we try it tough?

**Comment by trentwiles** [comment]
It won't work.

**Pull request closed without merging**
