### PR TITLE
Create credits.pug

### PR DESCRIPTION
**Pull request by ghost**
I'll add everyone soon.

### CODE REVIEW

**Comment by ghost** [comment]
Don't merge until i finish!

**Comment by ghost** [comment]
Now i just need to add the links, stay tight!

**Comment by ghost** [comment]
Done, you can merge now.

**Comment by trentwiles** [comment]
I was thinking of using the GitHub api to auto list each contributor.

**Comment by trentwiles** [comment]
https://api.github.com/repos/RiversideRocks/web-riverside/stats/contributors?anon=1

**Comment by ghost** [comment]
Oh

**Pull request closed without merging**
